baseURL = "https://trademonk-dev-theme.netlify.com/"
languageCode = "en-us"
title = "Restaurant"
theme = "trademonk-master-theme"

[params]
themeBgFrom = "#fffcfc"
themeBgTo = "#fafafa"
asideColor = "#000"